"""
Python Security Rules
~~~~~~~~~~~~~~~~~~~~~
50+ rules covering: SQLi, XSS, SSRF, SSTI, RCE, path traversal,
insecure deserialization, crypto weaknesses, logging, CORS, and more.
"""
from app.rules.base import Rule

RULES = [
    # ── SQL Injection ─────────────────────────────────────────────────────────
    Rule(
        id="PY_SQLI_001",
        title="SQL Injection — String Formatting in Query",
        description="User input is interpolated into a SQL query via f-string or % formatting. This allows SQL injection.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""(?:execute|executemany|raw|RawSQL)\s*\(\s*(?:f["']|["'][^"']*%s|["'][^"']*\{)""",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=0.85,
        remediation="Use parameterized queries: cursor.execute('SELECT * FROM t WHERE id=%s', (val,))",
        references=["https://owasp.org/www-community/attacks/SQL_Injection"],
    ),
    Rule(
        id="PY_SQLI_002",
        title="SQL Injection — .format() in Query String",
        description="SQL query built with .format() from user input.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""["'][^"']*(?:SELECT|INSERT|UPDATE|DELETE|WHERE)[^"']*["']\.format\s*\(""",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=0.85,
    ),
    # ── Command Injection ─────────────────────────────────────────────────────
    Rule(
        id="PY_CMDI_001",
        title="Command Injection — shell=True with Variable",
        description="subprocess called with shell=True and a non-literal command. User input in the command string leads to RCE.",
        category="injection",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""subprocess\.\w+\s*\([^)]*shell\s*=\s*True[^)]*\)""",
        negative_patterns=["#.*shell=True"],
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=0.8,
        remediation="Use list form: subprocess.run(['ls', '-la']) without shell=True.",
    ),
    Rule(
        id="PY_CMDI_002",
        title="Command Injection — os.system() Call",
        description="os.system() executes shell commands and is dangerous with user input.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""os\.system\s*\(""",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=0.7,
    ),
    Rule(
        id="PY_CMDI_003",
        title="Dangerous eval() Usage",
        description="eval() executes arbitrary Python code. If user-controlled input reaches eval, it results in RCE.",
        category="injection",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""\beval\s*\(""",
        negative_patterns=[r"#.*eval", r"ast\.literal_eval"],
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=0.75,
    ),
    Rule(
        id="PY_CMDI_004",
        title="Dangerous exec() Usage",
        description="exec() runs arbitrary Python code. RCE risk if user-controlled.",
        category="injection",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""\bexec\s*\(""",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=0.7,
    ),
    # ── SSTI ──────────────────────────────────────────────────────────────────
    Rule(
        id="PY_SSTI_001",
        title="Server-Side Template Injection — render_template_string()",
        description="render_template_string() renders arbitrary Jinja2 templates. If user input is included, SSTI and RCE are possible.",
        category="ssti",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""render_template_string\s*\(""",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=0.8,
        remediation="Use render_template() with static template files instead.",
        references=["https://portswigger.net/web-security/server-side-template-injection"],
    ),
    Rule(
        id="PY_SSTI_002",
        title="Server-Side Template Injection — Jinja2 Template from String",
        description="Jinja2 Template() or Environment().from_string() with user-controlled content leads to RCE.",
        category="ssti",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""(?:jinja2\.Template|Environment\(\)\.from_string)\s*\(""",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=0.85,
    ),
    # ── SSRF ──────────────────────────────────────────────────────────────────
    Rule(
        id="PY_SSRF_001",
        title="SSRF — requests.get/post with Potentially User-Controlled URL",
        description="HTTP request made with a URL variable. If the URL comes from user input without validation, SSRF is possible.",
        category="ssrf",
        severity="HIGH",
        languages=["python"],
        pattern=r"""requests\.\w+\s*\(\s*(?:url|target|endpoint|href)\b""",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=0.65,
        references=["https://portswigger.net/web-security/ssrf"],
    ),
    # ── Path Traversal ────────────────────────────────────────────────────────
    Rule(
        id="PY_PATH_001",
        title="Path Traversal — open() with Variable Path",
        description="File opened with a variable path. If user-controlled, path traversal (../../../etc/passwd) is possible.",
        category="path_traversal",
        severity="HIGH",
        languages=["python"],
        pattern=r"""\bopen\s*\(\s*(?:path|filename|filepath|file_path|name)\b""",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=0.6,
        remediation="Use os.path.abspath() and validate the path is within the expected directory.",
    ),
    Rule(
        id="PY_PATH_002",
        title="Path Traversal — send_file() with Variable",
        description="Flask send_file() with variable path. Use send_from_directory() with a safe base path.",
        category="path_traversal",
        severity="HIGH",
        languages=["python"],
        pattern=r"""send_file\s*\(\s*(?!['"])""",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=0.7,
    ),
    # ── Insecure Deserialization ──────────────────────────────────────────────
    Rule(
        id="PY_DESER_001",
        title="Insecure Deserialization — pickle.loads()",
        description="pickle.loads() deserializes arbitrary Python objects. Deserializing untrusted data leads to RCE.",
        category="injection",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""pickle\.loads?\s*\(""",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=0.85,
        remediation="Use JSON or other safe serialization formats. Never deserialize untrusted data with pickle.",
        references=["https://docs.python.org/3/library/pickle.html#restricting-globals"],
    ),
    Rule(
        id="PY_DESER_002",
        title="Insecure Deserialization — yaml.load() Without Loader",
        description="yaml.load() without a safe Loader allows arbitrary code execution via YAML payloads.",
        category="injection",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""yaml\.load\s*\([^)]*\)""",
        negative_patterns=[r"yaml\.load\s*\([^)]*Loader\s*=\s*yaml\.Safe"],
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=0.9,
        remediation="Use yaml.safe_load() instead of yaml.load().",
    ),
    # ── XXE ───────────────────────────────────────────────────────────────────
    Rule(
        id="PY_XXE_001",
        title="XXE — XML Parsing Without Disabling External Entities",
        description="XML parsed without disabling external entity processing. XXE can read server files or cause SSRF.",
        category="xxe",
        severity="HIGH",
        languages=["python"],
        pattern=r"""(?:etree\.parse|etree\.fromstring|minidom\.parse|parseString)\s*\(""",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=0.7,
        remediation="Use defusedxml library which disables external entity processing by default.",
        references=["https://github.com/tiran/defusedxml"],
    ),
    # ── Cryptography ──────────────────────────────────────────────────────────
    Rule(
        id="PY_CRYPTO_001",
        title="Weak Cryptography — MD5 Hash",
        description="MD5 is cryptographically broken and should not be used for security purposes.",
        category="cryptography",
        severity="MEDIUM",
        languages=["python"],
        pattern=r"""hashlib\.md5\s*\(""",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=0.9,
        remediation="Use hashlib.sha256() or better. For passwords, use bcrypt/argon2.",
    ),
    Rule(
        id="PY_CRYPTO_002",
        title="Weak Cryptography — SHA1 Hash",
        description="SHA1 is deprecated for security use.",
        category="cryptography",
        severity="LOW",
        languages=["python"],
        pattern=r"""hashlib\.sha1\s*\(""",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=0.85,
    ),
    Rule(
        id="PY_CRYPTO_003",
        title="Insecure Random — random.random() for Security",
        description="Python's random module is not cryptographically secure. Use secrets module for security tokens.",
        category="cryptography",
        severity="MEDIUM",
        languages=["python"],
        pattern=r"""random\.(?:random|randint|choice|sample|shuffle)\s*\(""",
        negative_patterns=["#.*random", "test_", "simulation", "game"],
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=0.6,
        remediation="Use secrets.token_hex() or secrets.token_urlsafe() for security tokens.",
    ),
    # ── JWT ───────────────────────────────────────────────────────────────────
    Rule(
        id="PY_JWT_001",
        title="JWT — verify=False Disables Signature Validation",
        description="JWT verification disabled. Any token, including forged ones, will be accepted.",
        category="authentication",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""(?:decode|verify)\s*\([^)]*verify\s*=\s*False""",
        cwe="CWE-347",
        owasp="A02:2021",
        confidence=0.95,
        references=["https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/"],
    ),
    Rule(
        id="PY_JWT_002",
        title="JWT — algorithms=['none'] Accepts Unsigned Tokens",
        description="Accepting 'none' algorithm allows authentication bypass via unsigned JWTs.",
        category="authentication",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""algorithms\s*=\s*\[["']none["']\]""",
        cwe="CWE-347",
        owasp="A02:2021",
        confidence=0.98,
    ),
    # ── CORS ──────────────────────────────────────────────────────────────────
    Rule(
        id="PY_CORS_001",
        title="Overly Permissive CORS — Allow All Origins",
        description="CORS configured to allow all origins (*). Any website can make authenticated cross-origin requests.",
        category="misconfiguration",
        severity="MEDIUM",
        languages=["python"],
        pattern=r"""(?:origins|allow_origins)\s*=\s*(?:\[?["']\*["']\]?|r"\.\*")""",
        cwe="CWE-942",
        owasp="A05:2021",
        confidence=0.85,
        remediation="Specify exact allowed origins instead of '*'.",
    ),
    # ── Debug/Logging ─────────────────────────────────────────────────────────
    Rule(
        id="PY_DEBUG_001",
        title="Flask Debug Mode Enabled",
        description="Flask running with debug=True exposes the Werkzeug debugger with RCE capability.",
        category="misconfiguration",
        severity="CRITICAL",
        languages=["python"],
        pattern=r"""app\.run\s*\([^)]*debug\s*=\s*True""",
        cwe="CWE-94",
        owasp="A05:2021",
        confidence=0.95,
        remediation="Set debug=False in production. Use environment variables to control this.",
    ),
    Rule(
        id="PY_LOG_001",
        title="Sensitive Data in Logging",
        description="Password, token, or secret being logged. Sensitive data may appear in log files.",
        category="data_exposure",
        severity="MEDIUM",
        languages=["python"],
        pattern=r"""(?:log(?:ger)?|print)\s*\([^)]*(?:password|passwd|token|secret|api_key|credential)""",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=0.7,
    ),
    # ── Open Redirect ─────────────────────────────────────────────────────────
    Rule(
        id="PY_REDIRECT_001",
        title="Open Redirect — Unvalidated Redirect URL",
        description="Redirect to a user-controlled URL. Attackers can redirect users to phishing sites.",
        category="misconfiguration",
        severity="MEDIUM",
        languages=["python"],
        pattern=r"""redirect\s*\(\s*(?:request\.|url|next|target|return_to)""",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=0.7,
        remediation="Validate redirect URLs against an allowlist of trusted domains.",
    ),
    # ── CSRF ──────────────────────────────────────────────────────────────────
    Rule(
        id="PY_CSRF_001",
        title="CSRF Protection Disabled",
        description="CSRF protection explicitly disabled. State-changing endpoints are vulnerable to cross-site request forgery.",
        category="misconfiguration",
        severity="HIGH",
        languages=["python"],
        pattern=r"""(?:csrf_exempt|CSRFExempt|csrf_disabled|WTF_CSRF_ENABLED\s*=\s*False)""",
        cwe="CWE-352",
        owasp="A01:2021",
        confidence=0.85,
    ),
    # ── SQL — Django ORM ──────────────────────────────────────────────────────
    Rule(
        id="PY_SQLI_003",
        title="SQL Injection — Django .extra() with User Input",
        description="Django's .extra() allows raw SQL injection when passed user-controlled values directly.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""\.extra\s*\(\s*(?:where|select|tables|order_by)\s*=""",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=0.75,
    ),
    # ── Hardcoded Secrets in Code ─────────────────────────────────────────────
    Rule(
        id="PY_SECRET_001",
        title="Hardcoded SECRET_KEY",
        description="Django or Flask SECRET_KEY hardcoded in source code.",
        category="secret",
        severity="HIGH",
        languages=["python"],
        pattern=r"""SECRET_KEY\s*=\s*["'][^"']{10,}["']""",
        negative_patterns=[r"os\.environ", r"getenv", r"config\[", r"settings\."],
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=0.8,
    ),
    # ── Prototype / Mass Assignment ───────────────────────────────────────────
    Rule(
        id="PY_MASSASSIGN_001",
        title="Mass Assignment — **request.json Direct Model Creation",
        description="Model created directly from request JSON. Attacker can set privileged fields.",
        category="business_logic",
        severity="HIGH",
        languages=["python"],
        pattern=r"""(?:Model|schema|db\.session\.add)\s*\(\s*\*\*\s*request\.""",
        cwe="CWE-915",
        owasp="A01:2021",
        confidence=0.8,
    ),
    # ── LDAP Injection ────────────────────────────────────────────────────────
    Rule(
        id="PY_LDAP_001",
        title="LDAP Injection",
        description="User input passed to LDAP search without escaping.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""ldap\d?\.search(?:_s)?\s*\([^)]*(?:request|input|user|query)""",
        cwe="CWE-90",
        owasp="A03:2021",
        confidence=0.7,
    ),
    # ── NoSQL Injection ───────────────────────────────────────────────────────
    Rule(
        id="PY_NOSQL_001",
        title="NoSQL Injection — MongoDB Query with User Input",
        description="MongoDB query built with unsanitized user input allows query manipulation.",
        category="injection",
        severity="HIGH",
        languages=["python"],
        pattern=r"""(?:find|find_one|update|delete)\s*\(\s*\{[^}]*(?:request|input)\.""",
        cwe="CWE-943",
        owasp="A03:2021",
        confidence=0.7,
    ),
]
