"""Infrastructure-as-Code security rules (Docker, Kubernetes, Terraform)"""
from app.rules.base import Rule

RULES = [
    Rule(id="IAC_DOCKER_001", title="Dockerfile — Running as Root",
         description="Container runs as root by default. Privilege escalation risk.",
         category="iac", severity="MEDIUM",
         pattern=r"""^FROM\s+\S+\s*$""",
         negative_patterns=[r"USER\s+(?!root)\w+"],
         cwe="CWE-250", owasp="A05:2021", confidence=0.5),
    Rule(id="IAC_DOCKER_002", title="Dockerfile — Hardcoded Secret in ENV",
         description="Secret hardcoded in Dockerfile ENV instruction.",
         category="secret", severity="HIGH",
         pattern=r"""ENV\s+\w*(?:PASSWORD|SECRET|KEY|TOKEN)\w*\s+\S+""",
         cwe="CWE-798", owasp="A02:2021", confidence=0.85),
    Rule(id="IAC_K8S_001", title="Kubernetes — Privileged Container",
         description="Pod running in privileged mode — full host access.",
         category="iac", severity="CRITICAL",
         pattern=r"""privileged\s*:\s*true""",
         cwe="CWE-250", owasp="A05:2021", confidence=0.9),
    Rule(id="IAC_K8S_002", title="Kubernetes — No Resource Limits",
         description="Container without CPU/memory limits can cause DoS.",
         category="iac", severity="LOW",
         pattern=r"""containers:\s*\n(?:(?!\s+resources:).)*$""",
         cwe="CWE-400", owasp="A05:2021", confidence=0.4),
    Rule(id="IAC_K8S_003", title="Kubernetes — Hardcoded Secret in Manifest",
         description="Secret value hardcoded in K8s manifest (should use Secrets).",
         category="secret", severity="HIGH",
         pattern=r"""(?:password|secret|token|key)\s*:\s*\S{8,}""",
         negative_patterns=[r"secretKeyRef", r"valueFrom"],
         cwe="CWE-798", owasp="A02:2021", confidence=0.7),
    Rule(id="IAC_TF_001", title="Terraform — Public S3 Bucket",
         description="S3 bucket configured with public ACL.",
         category="iac", severity="HIGH",
         pattern=r"""acl\s*=\s*["']public-read""",
         cwe="CWE-732", owasp="A05:2021", confidence=0.9),
    Rule(id="IAC_TF_002", title="Terraform — Hardcoded Credentials",
         description="AWS credentials hardcoded in Terraform config.",
         category="secret", severity="CRITICAL",
         pattern=r"""(?:access_key|secret_key)\s*=\s*["'][A-Za-z0-9+/]{20,}""",
         cwe="CWE-798", owasp="A02:2021", confidence=0.85),
    Rule(id="IAC_TF_003", title="Terraform — Overly Permissive IAM Policy",
         description="IAM policy with wildcard actions and resources.",
         category="iac", severity="HIGH",
         pattern=r"""actions\s*=\s*\[\s*["']\*["']\s*\]""",
         cwe="CWE-732", owasp="A01:2021", confidence=0.85),
]
