"""PHP Security Rules"""
from app.rules.base import Rule

RULES = [
    Rule(id="PHP_SQLI_001", title="SQL Injection — mysql_query() with Variable",
         description="Direct user input in MySQL query = SQLi.",
         category="injection", severity="CRITICAL", languages=["php"],
         pattern=r"""mysql_query\s*\(\s*["'][^"']*["']\s*\.""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="PHP_SQLI_002", title="SQL Injection — $wpdb->query() with Concatenation",
         description="WordPress direct SQL without prepare() = SQLi.",
         category="injection", severity="HIGH", languages=["php"],
         pattern=r"""\$wpdb->(?:query|get_results|get_row)\s*\(\s*["'][^"']*["']\s*\.""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="PHP_CMDI_001", title="Command Injection — system()/exec() with User Input",
         description="Shell command executed with user input.",
         category="injection", severity="CRITICAL", languages=["php"],
         pattern=r"""(?:system|exec|shell_exec|passthru|popen)\s*\(\s*\$_""",
         cwe="CWE-78", owasp="A03:2021", confidence=0.9),
    Rule(id="PHP_XSS_001", title="XSS — echo/print with Unescaped Input",
         description="User input echoed without htmlspecialchars().",
         category="xss", severity="HIGH", languages=["php"],
         pattern=r"""echo\s+\$_(?:GET|POST|REQUEST|COOKIE)""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.9),
    Rule(id="PHP_LFI_001", title="Local File Inclusion",
         description="include/require with user-controlled path = LFI.",
         category="path_traversal", severity="CRITICAL", languages=["php"],
         pattern=r"""(?:include|require)(?:_once)?\s*\(\s*\$_""",
         cwe="CWE-98", owasp="A03:2021", confidence=0.9),
    Rule(id="PHP_DESER_001", title="PHP Object Injection — unserialize()",
         description="Deserializing user input can lead to arbitrary code execution via magic methods.",
         category="injection", severity="CRITICAL", languages=["php"],
         pattern=r"""unserialize\s*\(\s*\$_""",
         cwe="CWE-502", owasp="A08:2021", confidence=0.9),
    Rule(id="PHP_SSRF_001", title="SSRF — curl_exec() with User-Controlled URL",
         description="curl_exec with user URL = SSRF.",
         category="ssrf", severity="HIGH", languages=["php"],
         pattern=r"""curl_setopt\s*\([^,]+,\s*CURLOPT_URL\s*,\s*\$_""",
         cwe="CWE-918", owasp="A10:2021", confidence=0.85),
    Rule(id="PHP_XXE_001", title="XXE — simplexml_load_string() with External Entities",
         description="PHP XML parsing without disabling external entities.",
         category="xxe", severity="HIGH", languages=["php"],
         pattern=r"""simplexml_load_(?:string|file)\s*\(""",
         negative_patterns=[r"LIBXML_NOENT"],
         cwe="CWE-611", owasp="A05:2021", confidence=0.7),
    Rule(id="PHP_OPEN_REDIRECT_001", title="Open Redirect — header() with User Input",
         description="header('Location:') with user URL = open redirect.",
         category="misconfiguration", severity="MEDIUM", languages=["php"],
         pattern=r"""header\s*\(\s*["']Location:\s*["']\s*\.\s*\$_""",
         cwe="CWE-601", owasp="A01:2021", confidence=0.85),
]
