"""Java Security Rules"""
from app.rules.base import Rule

RULES = [
    Rule(id="JAVA_SQLI_001", title="SQL Injection — Statement.executeQuery with Concatenation",
         description="SQL built with string concatenation — SQLi risk.",
         category="injection", severity="HIGH", languages=["java"],
         pattern=r"""(?:executeQuery|executeUpdate|execute)\s*\(\s*["'][^"']*["']\s*\+""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="JAVA_SQLI_002", title="SQL Injection — createNativeQuery with User Input",
         description="createNativeQuery allows raw SQL. Concatenation = SQLi.",
         category="injection", severity="HIGH", languages=["java"],
         pattern=r"""createNativeQuery\s*\(\s*(?!["'][^"']*\?[^"']*["'])""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.75),
    Rule(id="JAVA_CMDI_001", title="Command Injection — Runtime.exec()",
         description="Runtime.exec() with user input = OS command injection.",
         category="injection", severity="CRITICAL", languages=["java"],
         pattern=r"""Runtime\.getRuntime\(\)\.exec\s*\(""",
         cwe="CWE-78", owasp="A03:2021", confidence=0.8),
    Rule(id="JAVA_CMDI_002", title="Command Injection — ProcessBuilder",
         description="ProcessBuilder with variable commands = RCE risk.",
         category="injection", severity="CRITICAL", languages=["java"],
         pattern=r"""new\s+ProcessBuilder\s*\(""",
         cwe="CWE-78", owasp="A03:2021", confidence=0.7),
    Rule(id="JAVA_XXE_001", title="XXE — DocumentBuilderFactory Without Hardening",
         description="XML parsed without disabling external entity processing — XXE risk.",
         category="xxe", severity="HIGH", languages=["java"],
         pattern=r"""DocumentBuilderFactory\.newInstance\s*\(\s*\)""",
         negative_patterns=[r"setFeature.*XMLConstants", r"setExpandEntityReferences.*false"],
         cwe="CWE-611", owasp="A05:2021", confidence=0.8),
    Rule(id="JAVA_DESER_001", title="Insecure Deserialization — ObjectInputStream",
         description="Deserializing untrusted data with ObjectInputStream leads to RCE.",
         category="injection", severity="CRITICAL", languages=["java"],
         pattern=r"""new\s+ObjectInputStream\s*\(""",
         cwe="CWE-502", owasp="A08:2021", confidence=0.75),
    Rule(id="JAVA_XSS_001", title="XSS — PrintWriter.write() with User Input",
         description="Response writer outputs user data without encoding — XSS.",
         category="xss", severity="HIGH", languages=["java"],
         pattern=r"""(?:getWriter|out)\.(?:write|println|print)\s*\(\s*(?:request|param|user)""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.7),
    Rule(id="JAVA_PATH_001", title="Path Traversal — new File() with User Input",
         description="File path from user input — traversal risk.",
         category="path_traversal", severity="HIGH", languages=["java"],
         pattern=r"""new\s+File\s*\(\s*(?:request|param|user|path)""",
         cwe="CWE-22", owasp="A01:2021", confidence=0.7),
    Rule(id="JAVA_CRYPTO_001", title="Weak Crypto — MD5/DES/RC4",
         description="Deprecated cryptographic algorithm in use.",
         category="cryptography", severity="MEDIUM", languages=["java"],
         pattern=r"""getInstance\s*\(\s*["'](?:MD5|DES|RC4|RC2|Blowfish)["']\s*\)""",
         cwe="CWE-327", owasp="A02:2021", confidence=0.9),
    Rule(id="JAVA_SQLI_003", title="SQL Injection — JPQL Concatenation",
         description="JPQL query built with string concatenation.",
         category="injection", severity="HIGH", languages=["java"],
         pattern=r"""createQuery\s*\(\s*["'][^"']*["']\s*\+""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.8),
]
