"""JavaScript / TypeScript / Node.js Security Rules"""
from app.rules.base import Rule

RULES = [
    Rule(id="JS_XSS_001", title="DOM XSS — innerHTML Assignment",
         description="Setting innerHTML with user-controlled data leads to DOM XSS.",
         category="xss", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""\.innerHTML\s*=(?!=)""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.8,
         remediation="Use textContent or DOMPurify.sanitize() before setting innerHTML."),
    Rule(id="JS_XSS_002", title="DOM XSS — document.write()",
         description="document.write() with user input causes XSS.",
         category="xss", severity="HIGH", languages=["javascript"],
         pattern=r"""document\.write\s*\(""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.75),
    Rule(id="JS_XSS_003", title="DOM XSS — eval() with User Input",
         description="eval() executes arbitrary JS. Never pass user input to eval().",
         category="injection", severity="CRITICAL", languages=["javascript", "typescript"],
         pattern=r"""\beval\s*\(""",
         negative_patterns=[r"//.*eval", r"jest\.fn"],
         cwe="CWE-95", owasp="A03:2021", confidence=0.7),
    Rule(id="JS_XSS_004", title="React — dangerouslySetInnerHTML Usage",
         description="dangerouslySetInnerHTML can cause XSS if the value is user-controlled.",
         category="xss", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""dangerouslySetInnerHTML\s*=\s*\{""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.75),
    Rule(id="JS_SQLI_001", title="SQL Injection — Template Literal in Query",
         description="Template literal used to build SQL query with variable — SQL injection risk.",
         category="injection", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""(?:query|execute|db\.run)\s*\(\s*`[^`]*\$\{""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="JS_SQLI_002", title="SQL Injection — String Concatenation in Query",
         description="SQL query built with + concatenation — injection risk.",
         category="injection", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""["'](?:SELECT|INSERT|UPDATE|DELETE|WHERE)[^"']*["']\s*\+""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="JS_CMDI_001", title="Command Injection — child_process.exec()",
         description="exec() with user-controlled input leads to OS command injection.",
         category="injection", severity="CRITICAL", languages=["javascript", "typescript"],
         pattern=r"""(?:child_process\.)?exec\s*\(""",
         negative_patterns=[r"execSync\s*\(\s*['\"]", r"jest\.fn"],
         cwe="CWE-78", owasp="A03:2021", confidence=0.7),
    Rule(id="JS_SSRF_001", title="SSRF — fetch() with Variable URL",
         description="fetch() with a variable URL. If user-controlled, SSRF is possible.",
         category="ssrf", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""\bfetch\s*\(\s*(?:url|endpoint|target|href|link)\b""",
         cwe="CWE-918", owasp="A10:2021", confidence=0.6),
    Rule(id="JS_SSRF_002", title="SSRF — axios with Variable URL",
         description="axios request with variable URL — possible SSRF.",
         category="ssrf", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""axios\.\w+\s*\(\s*(?:url|target|endpoint)\b""",
         cwe="CWE-918", owasp="A10:2021", confidence=0.65),
    Rule(id="JS_PATH_001", title="Path Traversal — fs.readFile() with Variable",
         description="File read with variable path. User input can traverse directories.",
         category="path_traversal", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""fs\.(?:readFile|writeFile|appendFile|unlink)\s*\(\s*(?:path|file|filename)\b""",
         cwe="CWE-22", owasp="A01:2021", confidence=0.65),
    Rule(id="JS_NOSQL_001", title="NoSQL Injection — MongoDB find() with User Input",
         description="MongoDB find() directly using req.body/params without sanitization.",
         category="injection", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""\.find(?:One)?\s*\(\s*req\.""",
         cwe="CWE-943", owasp="A03:2021", confidence=0.8),
    Rule(id="JS_NOSQL_002", title="NoSQL Injection — MongoDB $where Operator",
         description="$where operator executes JavaScript. User input here = JS injection.",
         category="injection", severity="CRITICAL", languages=["javascript", "typescript"],
         pattern=r"""\$where\s*:""",
         cwe="CWE-943", owasp="A03:2021", confidence=0.9),
    Rule(id="JS_JWT_001", title="JWT — Insecure Secret",
         description="JWT signed with short or obvious secret.",
         category="authentication", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""jwt\.sign\s*\([^,]+,\s*["'][^"']{0,20}["']""",
         cwe="CWE-347", owasp="A02:2021", confidence=0.7),
    Rule(id="JS_JWT_002", title="JWT — No Algorithm Specified (none attack)",
         description="JWT decoded without specifying allowed algorithms enables none algorithm bypass.",
         category="authentication", severity="CRITICAL", languages=["javascript", "typescript"],
         pattern=r"""jwt\.verify\s*\([^)]*\)\s*;?\s*$""",
         negative_patterns=[r"algorithms\s*:", r"algorithm\s*:"],
         cwe="CWE-347", owasp="A02:2021", confidence=0.65),
    Rule(id="JS_PROTO_001", title="Prototype Pollution — Unsafe Object Merge",
         description="Recursive merge of user-controlled object into existing object can pollute Object.prototype.",
         category="injection", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""(?:_.merge|_.extend|merge|deepMerge)\s*\([^,]+,\s*req\.""",
         cwe="CWE-1321", owasp="A08:2021", confidence=0.8,
         references=["https://portswigger.net/daily-swig/prototype-pollution"]),
    Rule(id="JS_HARDCODE_001", title="Hardcoded Credentials in JS",
         description="Hardcoded password or API key found in JavaScript source.",
         category="secret", severity="HIGH", languages=["javascript", "typescript"],
         pattern=r"""(?:password|api_key|apiKey|secret|token)\s*[:=]\s*["'][^"']{8,}["']""",
         negative_patterns=[r"process\.env", r"config\.", r"getenv", r"placeholder"],
         cwe="CWE-798", owasp="A02:2021", confidence=0.7),
    Rule(id="JS_OPEN_REDIRECT_001", title="Open Redirect — Unvalidated URL",
         description="res.redirect() with user-controlled URL allows open redirect.",
         category="misconfiguration", severity="MEDIUM", languages=["javascript", "typescript"],
         pattern=r"""res\.redirect\s*\(\s*req\.""",
         cwe="CWE-601", owasp="A01:2021", confidence=0.85),
    Rule(id="JS_CORS_001", title="Overly Permissive CORS",
         description="CORS set to allow all origins.",
         category="misconfiguration", severity="MEDIUM", languages=["javascript", "typescript"],
         pattern=r"""origin\s*:\s*["']\*["']""",
         cwe="CWE-942", owasp="A05:2021", confidence=0.85),
    Rule(id="JS_CRYPTO_001", title="Weak Crypto — MD5",
         description="MD5 is not secure for cryptographic use.",
         category="cryptography", severity="MEDIUM", languages=["javascript", "typescript"],
         pattern=r"""(?:createHash|md5)\s*\(\s*["']md5["']\s*\)""",
         cwe="CWE-327", owasp="A02:2021", confidence=0.9),
    Rule(id="JS_REGEX_DOS_001", title="ReDoS — Potentially Vulnerable Regex",
         description="Complex nested regex quantifiers can cause catastrophic backtracking (ReDoS).",
         category="misconfiguration", severity="LOW", languages=["javascript", "typescript"],
         pattern=r"""(?:/|\bRegExp\s*\()[^/]*(?:\+|\*)\)\+""",
         cwe="CWE-400", owasp="A05:2021", confidence=0.5),
]
