"""Go Security Rules"""
from app.rules.base import Rule

RULES = [
    Rule(id="GO_SQLI_001", title="SQL Injection — db.Query with fmt.Sprintf",
         description="SQL built with fmt.Sprintf and user input = SQLi.",
         category="injection", severity="HIGH", languages=["go"],
         pattern=r"""db\.(?:Query|Exec|QueryRow)\s*\(\s*fmt\.Sprintf\s*\(""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.9),
    Rule(id="GO_SQLI_002", title="SQL Injection — String Concatenation in Query",
         description="Query built with + concatenation.",
         category="injection", severity="HIGH", languages=["go"],
         pattern=r"""db\.(?:Query|Exec|QueryRow)\s*\(\s*["'][^"']*["']\s*\+""",
         cwe="CWE-89", owasp="A03:2021", confidence=0.85),
    Rule(id="GO_CMDI_001", title="Command Injection — exec.Command with Variable",
         description="os/exec with user-controlled arguments = RCE.",
         category="injection", severity="CRITICAL", languages=["go"],
         pattern=r"""exec\.Command\s*\(\s*\w+""",
         negative_patterns=[r'exec\.Command\s*\(\s*"'],
         cwe="CWE-78", owasp="A03:2021", confidence=0.7),
    Rule(id="GO_PATH_001", title="Path Traversal — os.Open() with Variable",
         description="File opened with user-controlled path.",
         category="path_traversal", severity="HIGH", languages=["go"],
         pattern=r"""os\.(?:Open|Create|Remove|ReadFile)\s*\(\s*\w+""",
         negative_patterns=[r'os\.Open\s*\(\s*"'],
         cwe="CWE-22", owasp="A01:2021", confidence=0.6),
    Rule(id="GO_SSRF_001", title="SSRF — http.Get() with Variable URL",
         description="HTTP request with user-controlled URL.",
         category="ssrf", severity="HIGH", languages=["go"],
         pattern=r"""http\.(?:Get|Post)\s*\(\s*\w+""",
         negative_patterns=[r'http\.Get\s*\(\s*"'],
         cwe="CWE-918", owasp="A10:2021", confidence=0.65),
    Rule(id="GO_CRYPTO_001", title="Weak Crypto — MD5/SHA1",
         description="MD5 or SHA1 used for security purpose.",
         category="cryptography", severity="MEDIUM", languages=["go"],
         pattern=r"""(?:md5|sha1)\.New\s*\(\s*\)""",
         cwe="CWE-327", owasp="A02:2021", confidence=0.8),
    Rule(id="GO_TAINT_001", title="Template Injection — html/template with User Data",
         description="Go text/template (not html/template) is not XSS-safe.",
         category="xss", severity="HIGH", languages=["go"],
         pattern=r""""text/template"[^}]+\.Execute\s*\(""",
         cwe="CWE-79", owasp="A03:2021", confidence=0.7),
]
